//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MlsaGreenathon.Api.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MlsaGreenathon.Api.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Code&quot;: &quot;AF&quot;, &quot;Name&quot;: &quot;Afghanistan&quot;},{&quot;Code&quot;: &quot;AX&quot;, &quot;Name&quot;: &quot;\u00c5land Islands&quot;},{&quot;Code&quot;: &quot;AL&quot;, &quot;Name&quot;: &quot;Albania&quot;},{&quot;Code&quot;: &quot;DZ&quot;, &quot;Name&quot;: &quot;Algeria&quot;},{&quot;Code&quot;: &quot;AS&quot;, &quot;Name&quot;: &quot;American Samoa&quot;},{&quot;Code&quot;: &quot;AD&quot;, &quot;Name&quot;: &quot;Andorra&quot;},{&quot;Code&quot;: &quot;AO&quot;, &quot;Name&quot;: &quot;Angola&quot;},{&quot;Code&quot;: &quot;AI&quot;, &quot;Name&quot;: &quot;Anguilla&quot;},{&quot;Code&quot;: &quot;AQ&quot;, &quot;Name&quot;: &quot;Antarctica&quot;},{&quot;Code&quot;: &quot;AG&quot;, &quot;Name&quot;: &quot;Antigua and Barbuda&quot;},{&quot;Code&quot;: &quot;AR&quot;, &quot;Name&quot;: &quot;Argentina&quot;},{&quot;Code&quot;: &quot;AM&quot;, &quot;Name&quot;: &quot;Armenia&quot;},{&quot;Code&quot;: &quot;AW&quot;, &quot;Name&quot;: &quot;Aruba&quot;},{&quot;Code&quot;: &q....
        /// </summary>
        public static string Countries_Iso_3166_1 {
            get {
                return ResourceManager.GetString("Countries_Iso_3166_1", resourceCulture);
            }
        }
    }
}
